name: CI – Admojo-web

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm version 9.15.2
        run: npm install -g pnpm@9.15.2

      - name: Install dependencies
        run: pnpm install
        
      # Removed pnpm tests for now
      # - name: Run Tests
      #   run: pnpm run test
